platform:ios, '8.0'
target 'baisibudejie' do
    pod "AFNetworking"
#    pod "SDWebImage"
    pod "SVProgressHUD"
    pod “MJExtension”
    pod “MJRefresh”
#    pod "DACircularProgress"
    pod "pop"
end
